import { strictEqual, match } from "node:assert/strict";
import { describe, it } from "node:test";
import { generateEnvExample } from "./env-example.js";

describe("generateEnvExample", () => {
  it("emits manifest entries with description and tag", () => {
    const out = generateEnvExample({
      manifestEnv: {
        WORKDIR: {
          description: "Where projects live",
          example: "/tmp/work",
          secret: false,
          optional: false,
        },
        SECRET: { description: "A secret", secret: true, optional: true },
      },
      workflowEnvKeys: {},
      agentEnvKeys: {},
    });
    match(out, /# Where projects live/);
    match(out, /\[required\]/);
    match(out, /WORKDIR=\/tmp\/work/);
    match(out, /\[secret\]\[optional\]/);
    match(out, /SECRET=/);
  });

  it("auto-generates description for envKeys not in manifest", () => {
    const out = generateEnvExample({
      manifestEnv: {},
      workflowEnvKeys: { JIRA_API_TOKEN: ["ship-ticket"] },
      agentEnvKeys: { JIRA_API_TOKEN: ["jira-ticket-reader"] },
    });
    match(out, /# Required by agent jira-ticket-reader, workflow ship-ticket/);
    match(out, /JIRA_API_TOKEN=/);
  });

  it("manifest description wins over autogenerated", () => {
    const out = generateEnvExample({
      manifestEnv: {
        TOKEN: { description: "Actual description", secret: true, optional: false },
      },
      workflowEnvKeys: { TOKEN: ["wf"] },
      agentEnvKeys: {},
    });
    match(out, /# Actual description/);
    strictEqual(/Required by/.test(out), false);
  });

  it("orders entries: manifest first (alphabetical), then envKeys-only (alphabetical)", () => {
    const out = generateEnvExample({
      manifestEnv: { B_MANIFEST: { description: "b", secret: false, optional: false } },
      workflowEnvKeys: { Z_KEY: ["wf"], A_KEY: ["wf"] },
      agentEnvKeys: {},
    });
    const order = out
      .split("\n")
      .filter((l) => /^[A-Z_]+=/.test(l))
      .map((l) => l.split("=")[0]);
    strictEqual(order[0], "B_MANIFEST");
    strictEqual(order[1], "A_KEY");
    strictEqual(order[2], "Z_KEY");
  });
});
