import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import type { WorkflowDef } from "../define.js";

export interface GenerateSlashCommandsInput {
  workflows: WorkflowDef[];
  destDir: string;
}

export function generateSlashCommands(input: GenerateSlashCommandsInput): void {
  mkdirSync(input.destDir, { recursive: true });
  for (const wf of input.workflows) {
    const path = join(input.destDir, `${wf.name}.md`);
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, renderSlashCommand(wf), "utf8");
  }
}

function renderSlashCommand(wf: WorkflowDef): string {
  const required = wf.required ?? [];
  const variables = Object.keys(wf.variables ?? {});
  const argumentHint = required.length
    ? required.map((r) => `--${r} <value>`).join(" ")
    : "[--<var> <value>]";
  return `---
description: ${wf.description}
argument-hint: ${argumentHint}
---
<!-- Generated by 'generata skills sync' from agents/${wf.name}.ts. -->
<!-- Hand edits will be overwritten on next sync. Edit the workflow's description instead. -->

Run the \`${wf.name}\` workflow.

Required: ${required.join(", ") || "(none)"}
Variables: ${variables.join(", ") || "(none)"}

Use the Bash tool to execute:

\`pnpm generata ${wf.name} $ARGUMENTS\`
`;
}
